apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider=openshift
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: products-api
  name: products-api
spec:
  replicas: 1
  selector:
    io.kompose.service: products-api
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: products-api
    spec:
      containers:
      - env:
        - name: BASE_URL
          value: localhost
        - name: REDIS
          value: redis
        image: ' '
        name: products-api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - products-api
      from:
        kind: ImageStreamTag
        name: products-api:latest
    type: ImageChange
status: {}
