apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mikebild/web-app
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
